### ISSUE TITLE
HTTP vs HTTPS

### ISSUE THREAD

**Issue by foffux** [apptality/ATAppUpdater#10]
Hello
I have to ask you about Https support introduced with iOS 9. What I can see from your code is the following:

``` javascript
NSURL *lookupURL = [NSURL URLWithString:[NSString stringWithFormat:@"http://itunes.apple.com/lookup?bundleId=%@", bundleIdentifier]];
```

So you use Http. What about Https? Have you to distinguish among iOS version also?
Same question about:

``` javascript
const char *host = "itunes.apple.com";
```

Always speaking about connectivity checking: why did you use Apple site? Is it safe enough? Why not Google, for example?

Thank you very much.

**Comment by emotality** [comment]
Hi foffux!

You can use https if you want? Don't think it matters as you only do a GET request and no sensitive information is being sent or received as this is the same information on the AppStore, open to the public.

And I am just pinging the `itunes.apple.com` server to see if it's live, because if I ping Google server and it works doesn't mean the iTunes server is working and your app might or might not crash. We are pulling info from iTunes server so we need to see if that server is up, no matter if Google servers work or not.

Did this answer your questions? :blush:

**Comment by foffux** [comment]
Hello
I got it
I guess you answered all my questions.
So, from what you told me, I will use your pod as it is since it should work, right?
Thank you and great job
Bye

**Comment by emotality** [comment]
Well yes, 116 starred it and I'm sure they are using it :yum:
And there has been a few issues that has been resolved and contributions that improved the product.
Thanks! :blush:

**Comment by foffux** [comment]
Hello
just one small thing: how can I test your pod in my simulator? Before going live etc etc
thanks

**Comment by emotality** [comment]
Change your project's app version lower than the one that is currently on the AppStore, so that the AppStore version number is greater than your current version.

If you don't have your app on the AppStore then I'm afraid you cant really test it with your bundle identifier as it doesn't exist until you uploaded. But I can guarantee it will work! :blush:

**Comment by foffux** [comment]
Ok, then I will trust you
sorry for annoying you but app updating is very important
thank you

**Comment by emotality** [comment]
No problem, thanks for using it! :yum:
